version: '3'
services:
  database:
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "3307:3306"
    restart: on-failure:5
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_USER: "wordpress"
      MYSQL_DATABASE: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      MYSQL_ROOT_PASSWORD: "wordpress"
    
  phpfpm:
    depends_on:
      - database
    volumes:
      - "./site:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    restart: always
    image: 10up/phpfpm:latest
  
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "8000:80"
    image: nginx:latest
    volumes:
      - "./site:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always
  
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: on-failure:5
    environment:
      PMA_HOST: "database"
  
  wordmove:
    tty: true
    depends_on:
      - phpfpm
    image: welaika/wordmove
    restart: on-failure:5
    volumes:
      - ./site:/var/www/html
      - ./config/wordmove/:/html/
      - ./config/ssh:/root/.ssh

